---
title: "Untitled"
author: "Zidong Xu"
date: "2/4/2022"
output: html_document
---

```{r }
install.packages('timeDate')
library(tidyverse)
library(ggplot2)
library(forecast)
library(astsa) 
library(xts)
library(tseries)
library(fpp2)
library(fma)
library(lubridate)
library(TSstudio)
library(quantmod)
library(tidyquant)
library(plotly)
require(timeDate)
```

```{r }
sp_WKA <- read.csv(file = './stock_price/df_sp_WKA.csv')
head(sp_WKA)
tail(sp_WKA)
# convert DATE to Date class
sp_WKA$X <- as.Date(sp_WKA$X)
str(sp_WKA)

# loads/attaches xts
library(PerformanceAnalytics)  

# create xts object
par(mfrow=c(3,1))
par(pin = c(5,0.24))

sp_WKA_close <- xts(sp_WKA$close,sp_WKA$X)
plot(sp_WKA_close, 
     major.ticks="years", minor.ticks=NULL,
     grid.ticks.on="years", main="sp_WKA_close")
# difference 
dff1 = diff(sp_WKA_close)
plot(dff1, main="1st Order Differencing")
dff2 = diff(log(sp_WKA_close))
plot(dff2, main="diff_log transformation")

# acf
par(mfrow=c(3,1))
par(pin = c(5,0.4))

acf(sp_WKA_close)
acf(diff(sp_WKA_close, lag=1)[-1])
acf(diff(log(sp_WKA_close))[-1])

# pacf
pacf(sp_WKA_close)

# Reduce frequency to weekly data
sp_WKA_close_week <- to.weekly(sp_WKA_close)

```
```{r }
x <- window(sp_WKA_close)
forecast::gglagplot(x, do.lines = FALSE, lags=1)
forecast::gglagplot(x, do.lines = FALSE)
```

```{r }
(r = round(acf(sp_WKA_close, 6, plot=FALSE)$acf[-1], 3))
```

```{r }
# decomposition
plot(sp_WKA_close, 
     major.ticks="years", minor.ticks=NULL,
     grid.ticks.on="years", main="sp_WKA_close")

# detect the trend
trend_WKA = forecast::ma(sp_WKA_close, order = 365, centre = T)
plot(sp_WKA_close)

plot(trend_WKA)

# detrend the time series
detrend_WKA_1 = sp_WKA_close-trend_WKA
plot(detrend_WKA_1)

detrend_WKA_2 = sp_WKA_close/trend_WKA
plot(detrend_WKA_2)


```

```{r }
# downlown MSFT form yahoo
MSFT <- quantmod::getSymbols("MSFT", src="yahoo", auto.assign = FALSE)

# candle chart
quantmod::chartSeries(MSFT, theme="white", name="Microsoft",
                      subset="2010-01-01/2022-01-01")
quantmod::chartSeries(MSFT, type="line", TA="addSMA(14)",
                      subset="last 3 years",
                      theme="white", name="Microsoft")
```

```{r }
AAPL <- quantmod::getSymbols("AAPL", src="yahoo", auto.assign=FALSE)

# log rate of return
logret.AAPL <- diff(log(AAPL$AAPL.Adjusted))*100 
quantmod::chartSeries(logret.AAPL, type="l", TA=NULL,
                      subset="2019-01-01/2022-01-01",
                      name="Apple Log Returns",
                      theme="white", major.ticks="years",
                      minor.ticks=FALSE)

# Histogram log rate of return
x <- coredata(logret.AAPL)
hist(x, main="Apple Log Returns", xlab="", ylab="")

# Q-Q plot
qqnorm(x, main="Apple Log Returns")
qqline(x, col="red")
```


```{r }
# ggplot2 for VIS

df_mac_industry_area_estate_invest_month <- read.csv(file = 'df_mac_industry_area_estate_invest_month.csv')
head(df_mac_industry_area_estate_invest_month)

# Beijing
df_Beijing <- df_mac_industry_area_estate_invest_month %>%
  filter(area_name=='北京市') %>%
  select(stat_month, invest) 

ggplot(df_Beijing, aes(stat_month,invest))+geom_line(group = 1)+
  ggtitle("Beijing estate month investment (100 million)") +
  xlab("stat_month")+
  ylab("invest")+geom_point(color="purple")+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

# Hunan Province
df_Hunan <- df_mac_industry_area_estate_invest_month %>%
  filter(area_name=='湖南省') %>%
  select(stat_month, invest) 

ggplot(df_Hunan, aes(stat_month,invest))+geom_line(group = 1)+
  ggtitle("Hunan Province estate month investment (100 million)") +
  xlab("stat_month")+
  ylab("invest")+geom_point(color="lightgreen")+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
  
```

```{r }
# transform to ts data
# No January data
# Beijing
df_Beijing <- df_mac_industry_area_estate_invest_month %>%
  filter(area_name=='北京市') %>%
  select(invest) 

df_Beijing.ts=ts(df_Beijing, start = decimal_date(as.Date("2000-02-01")),frequency = 11)
str(df_Beijing.ts)

# Hunan
df_Hunan <- df_mac_industry_area_estate_invest_month %>%
  filter(area_name=='湖南省') %>%
  select(invest) 

df_Hunan.ts=ts(df_Hunan, start = decimal_date(as.Date("2000-02-01")),frequency = 11)
str(df_Hunan.ts)

autoplot(df_Beijing.ts, series = "Beijing")+
  autolayer(df_Hunan.ts, series = "Hunan")+
  xlab("Year")+
  ylab("Invest")+
  scale_color_manual(values = c("Beijing"="purple","Hunan"="grey50"),
                     breaks = c("Beijing","Hunan"))+
  ggtitle("Beijing_Hunan Province estate month invest (100 million)")
```
```{r }
# Lag
gglagplot(df_Beijing.ts, do.lines=FALSE, lag=1)
gglagplot(df_Beijing.ts, do.lines=FALSE)
ts_lags(df_Beijing.ts, lags = 11)

(r = round(acf(df_Beijing.ts, 15, plot=FALSE)$acf[-1], 3))
```

```{r }
# Decompose
# Additive
decompose_Beijing <- decompose(df_Beijing.ts, "additive")
plot(decompose_Beijing)

# Multiplicative
decompose_Beijing <- decompose(df_Beijing.ts, "multiplicative")
plot(decompose_Beijing)

```

```{r }
# ACF
ggAcf(df_Beijing.ts)

# PACF
ggPacf(df_Beijing.ts)

# Dickey-Fuller Test 
adf.test(df_Beijing.ts)
# p-value = .01>.05, we cannot reject the ho, thus our data is not stationary,
```

```{r }
# Detrending Data
diff_Beijing.ts_1 <- diff(df_Beijing.ts)
diff_Beijing.ts_2 <- diff(diff(df_Beijing.ts))
acf(diff_Beijing.ts_1)
ggAcf(diff_Beijing.ts_1)

plot(diff_Beijing.ts_1, main ="1st Order Differencing")
plot(diff_Beijing.ts_2, main ="2nd Order Differencing")

dff_log_Bejing.ts_3 <- diff(log(df_Beijing.ts))
plot(dff_log_Bejing.ts_3,main ="log transfer_Differencing")
```

```{r }
# Detrending Data
summary(fit <- lm(df_Beijing.ts~time(df_Beijing.ts), na.action=NULL))

plot(df_Beijing.ts, ylab="Invest",col=4, main="TBeijing Province estate month invest (100 million)")
abline(fit) # add the fitted line

par(mfrow=c(2,1))
plot(resid(fit), main="detrended")
plot(diff(df_Beijing.ts), main="first difference")

acf(resid(fit), 48, main="detrended")
acf(diff(df_Beijing.ts), 48, main="first difference")

x<-diff(df_Beijing.ts,5)
acf(x)
```















